version: 1.0.3-alpha {build}

branches:
  only:
  - master
  - develop

skip_tags: true

configuration:
- Debug
- Release

platform: Any CPU

environment:
  COVERITY_TOKEN:
    secure: +pKv+MoLP8CwE7a1xblzApoNDjAfAN7WzgP5hNHKaOs=
  COVERITY_EMAIL:
    secure: 6zUyb+IRQkAbWNWP0T0sHw==

cache: packages -> **\packages.config

before_build:
- cmd: nuget restore

build:
  project: CloudFS.sln
  verbosity: normal

test:
  categories:
    except:
    - Online

after_test:
- cmd: >-
    IF %CONFIGURATION% NEQ Debug EXIT
    cov-build --dir cov-int msbuild CloudFS.sln /t:Rebuild /v:quiet /p:Configuration=%CONFIGURATION% /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
    7z a -r coverity.tar cov-int
    7z a coverity.tar.gz coverity.tar
    curl --form token=%COVERITY_TOKEN% --form email=%COVERITY_EMAIL% --form file=@coverity.tar.gz --form version="1.0.3-alpha" https://scan.coverity.com/builds?project=viciousviper/CloudFS

artifacts:
- path: cov-int\build-log.txt
  name: Coverity-Build-Log
