version: 1.0.0-alpha {build}

branches:
  only:
  - master
  - develop

configuration:
- Debug
- Release

platform: Any CPU

before_build:
- cmd: nuget restore

build:
  project: CloudFS.sln
  verbosity: detailed

test: off