version: 1.0.10-beta {build}

branches:
  only:
  - develop
  - master

skip_tags: true

configuration:
- Debug
- Release

platform: Any CPU

environment:
  COVERITY_TOKEN:
    secure: +pKv+MoLP8CwE7a1xblzApoNDjAfAN7WzgP5hNHKaOs=
  COVERITY_EMAIL:
    secure: 6zUyb+IRQkAbWNWP0T0sHw==

cache: packages -> **\packages.config

build_script:
- cmd: >-
    nuget restore

    cov-build --dir cov-int msbuild CloudFS.sln /p:UseSharedCompilation=false /verbosity:minimal /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
test:
  categories:
    except:
    - Online

after_test:
- cmd: >-
    IF %APPVEYOR_REPO_BRANCH% NEQ master
    IF %CONFIGURATION% NEQ Debug EXIT

    7z a -r coverity.zip cov-int

    curl --form token=%COVERITY_TOKEN% --form email=%COVERITY_EMAIL% --form file=@coverity.zip --form version="1.0.10-beta" https://scan.coverity.com/builds?project=%APPVEYOR_REPO_NAME%

artifacts:
- path: coverity.zip
  name: Coverity-Upload
