version: 1.0.2-alpha {build}

branches:
  only:
  - master
  - develop

skip_tags: true

configuration:
- Debug
- Release

platform: Any CPU

before_build:
- cmd: nuget restore

build:
  project: CloudFS.sln
  verbosity: normal

test:
  categories:
    except:
    - Online
